server {
    listen 80;
    listen [::]:80;
    server_name vst2t.i7yun.top;

    root /var/www/hero-lineup-web;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
